### ISSUE TITLE
Actions to build the image disabled

### ISSUE THREAD

**Issue by prannou29** [daniiiol/dependency-check-prepared#10]
Hello,
First, thank you for this image.
I realised that the GitHub Actions to build this image and push it to DockerHub are all disabled, so no new image is available on DockerHub.
Is it possible to activate the actions ?
Thank you in advance.

**Comment by daniiiol** [comment]
With pleasure!

I just wanted to see if anyone was still using the project ;-)

All workflows are now activated again. Have fun with the image!
